blogProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp')),
]

blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:id>/<slug:post>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/', views.post_share, name='post_share'),
    path('post/<int:post_id>/comment', views.post_comment, name='post_comment'),
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogapp_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blogapp:post_detail', args=[self.id, self.slug])
    

# Creating Comment model
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by{self.name} on {self.post}'

blogapp/forms.py
from django import forms
# import Comment Model
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST

# Create your views here.

def post_list(request):
    posts = Post.objects.all().filter(status=Post.Status.PUBLISHED)
    return render(request, 'blogapp/post/list.html', {'posts':posts})


def post_detail(request, id, post):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED, slug=post)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    return render(request, 'blogapp/post/detail.html', {'post':post, 'comments':comments, 'form':form})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post.post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blogapp/post/share.html', {'post':post, 'form':form, 'sent':sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    
    return render(request, 'blogapp/post/comment.html',{'post':post, 'form':form, 'comment':comment})

blogapp/templates/blogapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
</head>

<body>

    <!-- Main Content -->
    <div class="container-fluid">
        <nav class="navbar border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand">Navbar</a>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </nav>
        <div class="row mt-4">
            <!-- Blog Content -->
            <main class="col-md-8 ms-sm-auto col-lg-9 px-md-4">
                {% block content %}

                {% endblock %}
            </main>
            <!-- Sidenav -->
            <nav class=" me-4 col-md-3 col-lg-2 d-md-block bg-dark border-start sidebar collapse" id="sidebarMenu">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page"
                                href="{% url 'blogapp:post_list' %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                About
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                Contact
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                Categories
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                Archives
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>










    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>

</html>

blogapp/templates/blogapp/post/comment.html
{% extends 'blogapp/base.html' %}

{% block title %} Add a comment {% endblock %}

{% block content %}
{% if comment %}
<div class="blog-post">
    <h3 class="blog-post-title">

       Your Comment has been added.

    </h3>
   
    <a href="{{post.get_absolute_url}}">Back to the post</a>
    {% else %}

    {% include 'blogapp/post/includes/comment_form.html' %}

</div>
{% endif %}





{% endblock %}

blogapp/templates/blogapp/post/detail.html
{% extends 'blogapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{post.title}} {% endblock %}

{% block content %}

<div class="blog-post">
    <h3 class="blog-post-title">

        {{post.title}}

    </h3>
    <p class="blog-post-meta date">{{post.publish}} by {{post.author|title}}</p>
    <p>{{post.body|linebreaks}}</p>
    <a href="{% url 'blogapp:post_share' post.id %}">Share this post</a>

    {% with comments.count as total_comments %}
    <h2>
        {{total_comments}} comment {{total_comments|pluralize}}
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div>
        <p>
            Comment {{forloop.counter}} by {{comment.name}}
            {{comment.created}}
        </p>
        {{comment.body|linebreaks}}

    </div>
    {% empty %}
    <p>There are no comments.</p>
    {% endfor %}


</div>

{% include "blogapp/post/includes/comment_form.html" %}




{% endblock %}

blogapp/templates/blogapp/post/includes/comment_form.html
{% load crispy_forms_tags %}
<h2>Add a new comment</h2>

<form action="{% url 'blogapp:post_comment' post.id %}" method="post">
    {{form|crispy}}
    {% csrf_token %}
    <p><input type="submit" class="btn btn-primary" value="Add comment"></p>
</form>

blogapp/templates/blogapp/post/list.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block title %} My Blog {% endblock %}

{% block content %}

{% for post in posts %}
<div class="blog-post">
    <h3 class="blog-post-title">
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
    </h3>
    <p class="blog-post-meta date">{{post.publish}} by {{post.author|title}}</p>
    <p>{{post.body|truncatewords:30|linebreaks}}</p>

</div>
{% endfor %}







{% endblock %}

blogapp/templates/blogapp/post/share.html
{% extends 'blogapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Share a post {% endblock %}

{% block content %}

<div class="blog-post">
    <h2 class="blog-post-title"> {{post.title}} </h2>
    {% if sent %}
    <h3>
        E-mail successfully sent
    </h3>
    <p class="blog-post-meta">"{{post.title}}" was successfully sent to {{form.cleaned_data_to}}.</p>
    {% else %}
    <h3>Share "{{post.title}}" by e-mail </h3>

    <form action="" method="post">
        {{form|crispy}}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
</div>

{% endblock %}